### ISSUE TITLE
i got an error

### ISSUE THREAD

**Issue by sandesh1994** [OmkarPathak/django-notekeeper#5]
sande@DESKTOP-FVLUENO MINGW64 ~/Desktop/project/django-notekeeper-master/django-notekeeper-master/notekeeper
$ python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 60, in 
execute
    super().execute(*args, **options)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 67, in 
handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\sande\Desktop\project\django-notekeeper-master\django-notekeeper-master\notekeeper\notekeeper\settings.py", line 14, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sande\Desktop\project\django-notekeeper-master\django-notekeeper-master\notekeeper\manage.py", line 21, in <module>       
    main()
  File "C:\Users\sande\Desktop\project\django-notekeeper-master\django-notekeeper-master\notekeeper\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 375, in execute  
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 336, in run_from_argv
    connections.close_all()
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 219, in close_all
    for alias in self:
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 213, in __iter__
    return iter(self.databases)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\sande\Desktop\project\django-notekeeper-master\django-notekeeper-master\notekeeper\notekeeper\settings.py", line 14, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
![image](https://user-images.githubusercontent.com/75189243/100529730-7e042b00-3210-11eb-955d-be2de18bf44d.png)

**Comment by OmkarPathak** [comment]
@sandesh1994 please try re-installing all the requirements

**Comment by sandesh1994** [comment]
solved
